name: 'Set up MSVC environment'

inputs:
  arch:
    description: 'Target architecture'
    required: true

runs:
  using: composite
  steps:
    - name: Set up MSVC environment
      run: ${{ github.action_path }}\msvc-env.ps1 ${{ inputs.arch }}
      shell: pwsh

    - name: Add msvc problem matcher
      run: echo '::add-matcher::${{ github.action_path }}\msvc-problem-matcher.json'
      shell: pwsh

    - name: Add clang-cl problem matcher
      run: echo '::add-matcher::${{ github.action_path }}\clang-cl-problem-matcher.json'
      shell: pwsh
