name: 'Set up MSVC environment'

inputs:
  arch:
    description: 'Target architecture'
    required: false
    default: 'x64'

runs:
  using: composite
  steps:
    - name: Set up MSVC environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ inputs.arch }}

    - name: Add msvc problem matcher
      run: echo '::add-matcher::${{ github.action_path }}\msvc-problem-matcher.json'
      shell: pwsh

    - name: Add clang-cl problem matcher
      run: echo '::add-matcher::${{ github.action_path }}\clang-cl-problem-matcher.json'
      shell: pwsh
