name: 'Set up MSVC environment'

runs:
  using: composite
  steps:
    - name: Set up MSVC environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Add clang-cl problem matcher
      uses: equeim/clang-cl-problem-matcher@v1
